package entite;
// Generated 2018-09-27 18:59:22 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Categorie generated by hbm2java
 */
public class Categorie  implements java.io.Serializable {


     private short idcategorie;
     private String nomcategorie;
     private Set produits = new HashSet(0);

    public Categorie() {
    }

	
    public Categorie(short idcategorie) {
        this.idcategorie = idcategorie;
    }
    public Categorie(short idcategorie, String nomcategorie, Set produits) {
       this.idcategorie = idcategorie;
       this.nomcategorie = nomcategorie;
       this.produits = produits;
    }
   
    public short getIdcategorie() {
        return this.idcategorie;
    }
    
    public void setIdcategorie(short idcategorie) {
        this.idcategorie = idcategorie;
    }
    public String getNomcategorie() {
        return this.nomcategorie;
    }
    
    public void setNomcategorie(String nomcategorie) {
        this.nomcategorie = nomcategorie;
    }
    public Set getProduits() {
        return this.produits;
    }
    
    public void setProduits(Set produits) {
        this.produits = produits;
    }




}


