package entite;
// Generated 2018-09-06 20:59:46 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Commande generated by hbm2java
 */
public class Commande  implements java.io.Serializable {


     private BigDecimal nocommande;
     private Client client;
     private Facture facture;
     private Date datecommande;
     private Set ligneCommandes = new HashSet(0);

    public Commande() {
    }

	
    public Commande(BigDecimal nocommande) {
        this.nocommande = nocommande;
    }
    public Commande(BigDecimal nocommande, Client client, Facture facture, Date datecommande, Set ligneCommandes) {
       this.nocommande = nocommande;
       this.client = client;
       this.facture = facture;
       this.datecommande = datecommande;
       this.ligneCommandes = ligneCommandes;
    }
   
    public BigDecimal getNocommande() {
        return this.nocommande;
    }
    
    public void setNocommande(BigDecimal nocommande) {
        this.nocommande = nocommande;
    }
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }
    public Facture getFacture() {
        return this.facture;
    }
    
    public void setFacture(Facture facture) {
        this.facture = facture;
    }
    public Date getDatecommande() {
        return this.datecommande;
    }
    
    public void setDatecommande(Date datecommande) {
        this.datecommande = datecommande;
    }
    public Set getLigneCommandes() {
        return this.ligneCommandes;
    }
    
    public void setLigneCommandes(Set ligneCommandes) {
        this.ligneCommandes = ligneCommandes;
    }




}


