package entite;
// Generated 2018-09-06 20:59:46 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Facture generated by hbm2java
 */
public class Facture  implements java.io.Serializable {


     private BigDecimal idfacture;
     private Client client;
     private BigDecimal prixht;
     private BigDecimal prixttc;
     private Date datefacturation;
     private Set commandes = new HashSet(0);

    public Facture() {
    }

	
    public Facture(BigDecimal idfacture) {
        this.idfacture = idfacture;
    }
    public Facture(BigDecimal idfacture, Client client, BigDecimal prixht, BigDecimal prixttc, Date datefacturation, Set commandes) {
       this.idfacture = idfacture;
       this.client = client;
       this.prixht = prixht;
       this.prixttc = prixttc;
       this.datefacturation = datefacturation;
       this.commandes = commandes;
    }
   
    public BigDecimal getIdfacture() {
        return this.idfacture;
    }
    
    public void setIdfacture(BigDecimal idfacture) {
        this.idfacture = idfacture;
    }
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }
    public BigDecimal getPrixht() {
        return this.prixht;
    }
    
    public void setPrixht(BigDecimal prixht) {
        this.prixht = prixht;
    }
    public BigDecimal getPrixttc() {
        return this.prixttc;
    }
    
    public void setPrixttc(BigDecimal prixttc) {
        this.prixttc = prixttc;
    }
    public Date getDatefacturation() {
        return this.datefacturation;
    }
    
    public void setDatefacturation(Date datefacturation) {
        this.datefacturation = datefacturation;
    }
    public Set getCommandes() {
        return this.commandes;
    }
    
    public void setCommandes(Set commandes) {
        this.commandes = commandes;
    }




}


