package entite;
// Generated 2018-09-27 18:59:22 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Facture generated by hbm2java
 */
public class Facture  implements java.io.Serializable {


     private FactureId id;
     private Commande commande;
     private BigDecimal prixht;
     private BigDecimal prixttc;
     private Date datefacturation;

    public Facture() {
    }

	
    public Facture(FactureId id, Commande commande) {
        this.id = id;
        this.commande = commande;
    }
    public Facture(FactureId id, Commande commande, BigDecimal prixht, BigDecimal prixttc, Date datefacturation) {
       this.id = id;
       this.commande = commande;
       this.prixht = prixht;
       this.prixttc = prixttc;
       this.datefacturation = datefacturation;
    }
   
    public FactureId getId() {
        return this.id;
    }
    
    public void setId(FactureId id) {
        this.id = id;
    }
    public Commande getCommande() {
        return this.commande;
    }
    
    public void setCommande(Commande commande) {
        this.commande = commande;
    }
    public BigDecimal getPrixht() {
        return this.prixht;
    }
    
    public void setPrixht(BigDecimal prixht) {
        this.prixht = prixht;
    }
    public BigDecimal getPrixttc() {
        return this.prixttc;
    }
    
    public void setPrixttc(BigDecimal prixttc) {
        this.prixttc = prixttc;
    }
    public Date getDatefacturation() {
        return this.datefacturation;
    }
    
    public void setDatefacturation(Date datefacturation) {
        this.datefacturation = datefacturation;
    }




}


