package entite;
// Generated 2018-09-27 18:59:22 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * FactureId generated by hbm2java
 */
public class FactureId  implements java.io.Serializable {


     private BigDecimal idfacture;
     private BigDecimal nocommande;

    public FactureId() {
    }

    public FactureId(BigDecimal idfacture, BigDecimal nocommande) {
       this.idfacture = idfacture;
       this.nocommande = nocommande;
    }
   
    public BigDecimal getIdfacture() {
        return this.idfacture;
    }
    
    public void setIdfacture(BigDecimal idfacture) {
        this.idfacture = idfacture;
    }
    public BigDecimal getNocommande() {
        return this.nocommande;
    }
    
    public void setNocommande(BigDecimal nocommande) {
        this.nocommande = nocommande;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FactureId) ) return false;
		 FactureId castOther = ( FactureId ) other; 
         
		 return ( (this.getIdfacture()==castOther.getIdfacture()) || ( this.getIdfacture()!=null && castOther.getIdfacture()!=null && this.getIdfacture().equals(castOther.getIdfacture()) ) )
 && ( (this.getNocommande()==castOther.getNocommande()) || ( this.getNocommande()!=null && castOther.getNocommande()!=null && this.getNocommande().equals(castOther.getNocommande()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdfacture() == null ? 0 : this.getIdfacture().hashCode() );
         result = 37 * result + ( getNocommande() == null ? 0 : this.getNocommande().hashCode() );
         return result;
   }   


}


