package entite;
// Generated 2018-09-06 20:59:46 by Hibernate Tools 4.3.1

import java.math.BigDecimal;




/**
 * LigneCommande generated by hbm2java
 */
public class LigneCommande  implements java.io.Serializable {


     private LigneCommandeId id;
     private Commande commande;
     private Produit produit;
     private Integer quantite;
     
     private BigDecimal montantParProduit = new BigDecimal(0);

    public LigneCommande() {
    }

	
    public LigneCommande(LigneCommandeId id, Commande commande, Produit produit) {
        this.id = id;
        this.commande = commande;
        this.produit = produit;
    }
    public LigneCommande(LigneCommandeId id, Commande commande, Produit produit, Integer quantite) {
       this.id = id;
       this.commande = commande;
       this.produit = produit;
       this.quantite = quantite;
    }
   
    public LigneCommandeId getId() {
        return this.id;
    }
    
    public void setId(LigneCommandeId id) {
        this.id = id;
    }
    public Commande getCommande() {
        return this.commande;
    }
    
    public void setCommande(Commande commande) {
        this.commande = commande;
    }
    public Produit getProduit() {
        return this.produit;
    }
    
    public void setProduit(Produit produit) {
        this.produit = produit;
    }
    public Integer getQuantite() {
        return this.quantite;
    }
    
    public void setQuantite(Integer quantite) {
        this.quantite = quantite;
    }
    
    public void calculerMontantProduit()
    {
        montantParProduit = montantParProduit.add(this.getProduit().getPrix().multiply(new BigDecimal(this.getQuantite())));
    }




}


