package entite;
// Generated 2018-09-06 20:59:46 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Marque generated by hbm2java
 */
public class Marque  implements java.io.Serializable {


     private byte idmarque;
     private String nom;
     private Set produits = new HashSet(0);

    public Marque() {
    }

	
    public Marque(byte idmarque) {
        this.idmarque = idmarque;
    }
    public Marque(byte idmarque, String nom, Set produits) {
       this.idmarque = idmarque;
       this.nom = nom;
       this.produits = produits;
    }
   
    public byte getIdmarque() {
        return this.idmarque;
    }
    
    public void setIdmarque(byte idmarque) {
        this.idmarque = idmarque;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public Set getProduits() {
        return this.produits;
    }
    
    public void setProduits(Set produits) {
        this.produits = produits;
    }




}


