INSERT INTO CATEGORIE VALUES(1,'Repas');
INSERT INTO CATEGORIE VALUES(2,'Barre');
INSERT INTO CATEGORIE VALUES(3,'Boisson');
INSERT INTO CATEGORIE VALUES(4,'Capsule');
INSERT INTO CATEGORIE VALUES(5,'Poudre');


INSERT INTO MARQUE VALUES(1,'MuscleTech');
INSERT INTO MARQUE VALUES(2,'Mutant');
INSERT INTO MARQUE VALUES(3,'Believe Suppléments');
INSERT INTO MARQUE VALUES(4,'Muscle Mac');
INSERT INTO MARQUE VALUES(5,'Nutrition Fit Plus');
INSERT INTO MARQUE VALUES(6,'Quest Nutrition');
INSERT INTO MARQUE VALUES(7,'XYIENCE');
INSERT INTO MARQUE VALUES(8,'ABB Performance');


INSERT INTO PRODUIT VALUES (1,4,'Mac & Cheese','MUSCLE MAC ™ MACARONI & FROMAGES  Nos pâtes sont sans OGM et enrichies en protéines végétales ajoutées. Il a le goût que vous désirez plus une texture lisse. Notre fromage est réel, sans colorants synthétiques, couleurs ou saveurs',7.99,'11oz',400,'boite-1.jpg',1);
INSERT INTO PRODUIT VALUES (2,5,'Barre ProForce','Barre de protéines naturelles aux bleuets',42.00,'12 X 100g',400,'bleuet-2.png',2);
INSERT INTO PRODUIT VALUES (3,6,'Quest Bars','Les Quest Bars sont des barres riches en protéines, sans gluten et sans sucres ajoutés idéales en collation pour vous aider à atteindre vos objectifs sportifs ou autres!',60.00,'12 X 60g',400,'rdqb005_quest-bars-12-x-60g-peanut-butter-and-jelly.jpg',2);
INSERT INTO PRODUIT VALUES (4,7,'Xenergy RTD','Boisson XENERGY ™ Prime Energy Couleurs naturelles et Saveurs ZERO sucre Goût incroyable! Toutes les couleurs naturelles et Saveurs vous donne une dégustation de boisson étonnante d''énergie, sans les soucis associés à des couleurs artificielles.',48.00,'12X473mL',400,'xenergy-rtd.jpg',3);
INSERT INTO PRODUIT VALUES (5,8,'Pure Pro 35 Shake','Si riche, crémeux et délicieux, vous oubliez presque que vous êtes en train de boire une boisson protéinée. Mais avec 35 grammes dans chaque bouteille refermable, nous sommes convaincus des bienfaits. Pure Pro 35 shakes sont fabriqués avec les meilleurs protéines et sont faibles en gras et n''ont que 1 g de sucre',60.00 ,'12 X 354mL',400,'abb-performance-pure-pro-35-shake.jpg',3);
INSERT INTO PRODUIT VALUES (6,1,'MT Platinum - 100% Hydrolyzed Beef Protein','Platinum 100% Beef Protein fournit seulement de haute qualité, isolé protéine de boeuf qui a subi une hydrolyse avancée pour un produit fini qui offre tout ce que vous voulez et rien que vous ne le faites pas - comme la graisse, le sucre, le cholestérol, ou le lactose!',59.99,'2 lbs',400,'100-boeuf.jpg',5);
INSERT INTO PRODUIT VALUES (7,1,'Hydroxycut Drink Mix','Perte de Poids avancée Pas de sucre, seulement 10 calories par portion et bon goût Augmenter Energy Poussée Metabolism',39.99,'21 sachets',400,'81fstef24bl_sy355_.jpg',3);
INSERT INTO PRODUIT VALUES (8,1,'Performance Series Peak ATP','CARACTÉRISTIQUES ET AVANTAGES: Les sujets testés ont gagné 8,8 lbs. de la masse maigre, de force et de la performance.  Formulé avec Peak ATP® / MD  Cherché à l''Université de Tampa',55.99,'60 caps',400,'peak-atp.jpg',4);
INSERT INTO PRODUIT VALUES (9,3,'B6 + Magnesium','Le magnésium et B6 sont des nutriments essentiels pour les fonctions du corps. Le magnésium et B6 vont ensemble comme le beurre de cacahuète et la gelée. Ce combo aide votre digestion globale, l''absorption et l''utilisation de protéines, de graisses et d''hydrates de carbone et les transforme en énergie. Si votre corps n''a pas de nutriments énergétiques, vous pouvez développer des envies de nourriture, de l''anxiété, de l''hypoglycémie et une tendance à trop manger!',34.99,'120 caps',400,'magnesium-3.jpg',4);
INSERT INTO PRODUIT VALUES (10,3,'Carbs + Électrolytes','Electrolyte + glucides est un glucide glycémique à haute teneur en glucides qui est nécessaire pour reconstituer le glycogène musculaire que vous avez brûlé pendant l''effort. Depuis que nous avons ajouté des électrolytes à une portion de 45g de glucides, ce produit vous aidera à récupérer plus rapidement, mais aussi à alimenter vos entraînements les plus difficiles en offrant une très puissante portion de glucides + électrolytes à vos muscles!',63.99,'3.60 lbs',400,'carbs-electrolytes.png',5);
INSERT INTO PRODUIT VALUES (11,3,'Transparent 100 % Iso','Transparent 100% Iso - 1.76lb 8 portions  27g de protéines / portion Sans gras Sans sucre Sans lactose Sans gluten',69.99,'1.76 lbs',400,'transparent-2lb.png',5);
INSERT INTO PRODUIT VALUES (12,2,'Mutant Bcaa','MUTANT BCAA CAPS est constitué de  2000 mg de BCAAs par dose dans le rapport 2: 1: 1 préféré. De plus, nous avons conservé intacts les électrolytes minéraux essentiels et l''agent d''absorption breveté BioPerine® que nous utilisons également dans notre poudre MUTANT BCAA 9.7.',35.99,'200 caps',400,'bcaa200caps-1.jpg',4);
INSERT INTO PRODUIT VALUES (13,2,'Mutant Carnitine','MUTANT CARNITINE contient des taux prouvés (2250 mg par dose) de la forme stabilisée de L-Carnitine (L-Carnitine-L-Tartrate) et de l''agent d''absorption breveté BioPerine®, faisant de MUTANT CARNITINE une formule remarquable dans sa catégorie.',35.99,'120 caps',400,'carnitine-1.png',4);
INSERT INTO PRODUIT VALUES (14,2,'Mutant Madness','MUTANT MADNESS  avec sa nouvelle formulation améliorée saisit toute l''expérience de pré-entraînement, et l''apporte à un tout nouveau niveau extrême! Conçu exclusivement pour les séances d''entraînement de haute intensité seulement',71.99,'375 g',400,'madness-1.jpg',5);






