DROP TABLE CLIENT CASCADE CONSTRAINTS;
DROP TABLE COMMANDE CASCADE CONSTRAINTS;
DROP TABLE LIGNE_COMMANDE CASCADE CONSTRAINTS;
DROP TABLE CATEGORIE CASCADE CONSTRAINTS;
DROP TABLE PRODUIT CASCADE CONSTRAINTS;
DROP TABLE MARQUE CASCADE CONSTRAINTS;
DROP TABLE FACTURE CASCADE CONSTRAINTS;

CREATE TABLE CLIENT(
IDCLIENT NUMBER(20) CONSTRAINT PK_CLIENT PRIMARY KEY ,
NOMCLIENT VARCHAR(30) CONSTRAINT NN_NOMCLIENT NOT NULL,
PRENOMCLIENT VARCHAR(40) CONSTRAINT NN_PRENOMCLIENT NOT NULL,
COURIEL VARCHAR(40) CONSTRAINT NNU_COURRIEL NOT NULL UNIQUE,
MOTDEPASSE VARCHAR(40) CONSTRAINT NN_MOTDEPASSE NOT NULL,
TELEPHONECLIENT VARCHAR(15),
NOCIVIQUE VARCHAR (10),
NOAPP  VARCHAR(3),
NOMRUE VARCHAR(30),
VILLE VARCHAR(20),
PROVINCE VARCHAR(20),
PAYS VARCHAR(20)
);


CREATE  TABLE COMMANDE
( 
NOCOMMANDE NUMBER(30) PRIMARY KEY,
DATECOMMANDE DATE,
IDCLIENT NUMBER(20),
CONSTRAINT FK_COMMANDE FOREIGN KEY (IDCLIENT) REFERENCES CLIENT(IDCLIENT),
);

CREATE TABLE CATEGORIE(
IDCATEGORIE NUMBER(3) CONSTRAINT PK_CATEGORIE PRIMARY KEY,
NOMCATEGORIE VARCHAR(30)
);

CREATE TABLE MARQUE (
IDMARQUE NUMBER(2) PRIMARY KEY,
NOM VARCHAR(50)
);

CREATE TABLE PRODUIT(
IDPRODUIT  NUMBER(20) CONSTRAINT PK_PRODUIT PRIMARY KEY,
IDMARQUE NUMBER(2),
NOMPRODUIT VARCHAR(50),
DESCRIPTION_FR VARCHAR(500),
PRIX NUMBER(6,2),
FORMATPRO VARCHAR(10),
QUANTITEENSTOCK NUMBER(6),
image varchar(200),
IDCATEGORIE NUMBER(3),
CONSTRAINT FK_IDCATEGORIE FOREIGN KEY(IDCATEGORIE) REFERENCES CATEGORIE(IDCATEGORIE),
CONSTRAINT FK_IDMARQUE FOREIGN KEY(IDMARQUE) REFERENCES MARQUE(IDMARQUE)
);



CREATE TABLE LIGNE_COMMANDE (
NOCOMMANDE NUMBER(30), 
IDPRODUIT NUMBER(20),
QUANTITE NUMBER(5),
CONSTRAINT FK_NOCOMMANDE  FOREIGN KEY(NOCOMMANDE) REFERENCES COMMANDE(NOCOMMANDE),
CONSTRAINT FK_IDPRODUIT FOREIGN KEY(IDPRODUIT) REFERENCES PRODUIT(IDPRODUIT),
CONSTRAINT PK_LIGNE_COMMANDE PRIMARY KEY (NOCOMMANDE,IDPRODUIT)
);
CREATE TABLE FACTURE(
IDFACTURE NUMBER(30),
NOCOMMANDE NUMBER(30),
PRIXHT NUMBER(7,2),
PRIXTTC NUMBER(7,2),
DATEFACTURATION DATE,
CONSTRAINT FACTURE_ID_PK PRIMARY KEY (IDFACTURE,NOCOMMANDE),
CONSTRAINT FACTURE_NOCOMMANDE_FK FOREIGN KEY (NOCOMMANDE) REFERENCES COMMANDE(NOCOMMANDE)
);